name: lant
dependencies:
- appnope=0.1.0=py35_0
- decorator=4.0.10=py35_0
- ipython=5.0.0=py35_0
- ipython_genutils=0.1.0=py35_0
- openssl=1.0.2h=1
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.2=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.1.3=py35_0
- python=3.5.2=0
- python.app=1.2=py35_4
- pyyaml=3.11=py35_4
- readline=6.2=2
- setuptools=23.0.0=py35_0
- simplegeneric=0.8.1=py35_1
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.2.1=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - prompt-toolkit==1.0.3

